### ISSUE TITLE
padding & margin trumps only act on one side

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#128]
Each of our `padding`, `margin`, `no-padding`, `no-margin` classes acts on one side of the elements box model only — we at least need to also be able to set margins/padding on all sides at once e.g.

``` scss
.no-padding {
  padding: 0;
}

.padding {
  padding: $bitstyles-padding;
}
```
