### ISSUE TITLE
Add overflow object

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#260]
Used a several projects, especially those with app-like UIs:

```scss
// (1) Fixes bug in safari that causes the scrollbars to appear behind some content within the overflow element.

.o-overflow {
  max-height: 100%;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  transform: translateZ(0); // (1)
}
```
