### ISSUE TITLE
Add object-fit-cover object

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#261]
Commonly used for e.g. images/media content. Includes support for the [object-fit polyfill](https://github.com/bfred-it/object-fit-images) (JS), though that is maybe better achieved using [this post-css plugin](https://www.npmjs.com/package/postcss-object-fit-images) (does that fit our needs?).

```scss
.o-object-cover {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
  font-family: 'object-fit: cover;'; // Required for the polyfill
}

```
