### ISSUE TITLE
Add utility: font-family

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#583]
We have utility classes to set font-weight, font-style, and font-size, but not font-family. This should integrate with the existing font-stack & webfonts in `settings/typography` when useful, and to avoid duplication. Specifying a name and the font-stack something like

```scss
(
  'head': 'Nunito, sans-serif, Helvetica',
  'body': 'sans-serif, Helvetica'
)
```
to produce e.g.

```scss
.u-font-head {
  font-family: Nunito, sans-serif, Helvetica;
}

.u-font-body  {
  font-family: sans-serif, Helvetica;
}
```
