### ISSUE TITLE
Make heading line-heights overridable

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#596]
Right now the line-height of all elements is the same (unless using a line-height utility class). Many designs call for different line-height at each font-size though — it’d be great to be able to specify that on a per-font-size basis, and have it applied to the base styles for elements `h1` through `h6`, and the same utility classes.

Something like

```scss
$line-heights: (
  'h0': 0.9,
  'h1': 1.29,
  'h2': 1.2,
  'h3': 1.33,
  'h4': 1.5,
  'h5': 1.43,
  'h6': 1.67,
);

// …

h1 {
  line-height: map.get($line-heights, 'h1');
}
```

If possible integrate that into the current font-size generation, to avoid repetition. possibly it could also be included in the specification of font-sizes in `typography.$font-sizes`?
